resources:
  repositories:
    - repository: ESODevTools
      type: git
      name: ESODevTools
      ref: refs/heads/ado
name: $(BuildID)
trigger:
  - master
pr: none
variables:
  - group: TranslatorKey
jobs:
  - template: ci.yml@ESODevTools
