name: $(BuildID)
trigger:
- master
pr: none
jobs:
- job: Test
  pool:
    vmImage: 'Ubuntu-16.04'
  variables:
    - group: TranslatorKey

  steps:
    - script: |
        npm install
        npm test
      displayName: 'npm install and test'
      env: {
        "AzureTranslatorKey": $(ProvinatusTranslatorKey1)
      }

- job: Package
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
    - script: |
        npm install
        npm run build
      
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
