name: $(BuildID)
trigger: 
- master

pr: none

variables:
  - group: TranslatorKey

pool:
  vmImage: 'Ubuntu-16.04'

jobs:
  - job: Run Jest
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '8.x'
        displayName: 'Install Node.js'

      - script: |
          npm install
          npm test
        displayName: 'npm install and test'
        env: {
          "AzureTranslatorKey": $(ProvinatusTranslatorKey1)
        }
