name: $(BuildID)
trigger:
- master
pr: none
jobs:
- job: Test
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '8.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
        npm test
      displayName: 'npm install and test'
      env: {
        "AzureTranslatorKey": $(ProvinatusTranslatorKey1)
      }

- job: Package
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
    - task: CopyFiles@2
      displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
      inputs:
        Contents: |
         test/**
         index.js
         package-lock.json
         package.json
         translate.js
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
      
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
        #artifactName: 'drop' 
        #publishLocation: 'Container' # Options: container, filePath
        #targetPath: # Required when publishLocation == FilePath
        #parallel: false # Optional
        #parallelCount: # Optional