resources:
  repositories:
    - repository: ESODevTools
      type: git
      name: ESODevTools
      ref: refs/heads/ado
name: $(BuildID)
trigger: none
pr:
  - master
jobs:
  - template: ./.ADO/pr.yml@ESODevTools
