resources:
  repositories:
    - repository: ESODevTools
      type: git
      name: ESODevTools
      ref: refs/heads/ado
name: $(BuildID)
trigger: none
pr:
  - master

variables:
  - group: TranslatorKey


jobs:
  - variables:
      AzureTranslatorKey: $(ProvinatusTranslatorKey1)
  - template: ./.ADO/pr.yml@ESODevTools
