resources:
  repositories:
    - repository: ESODevTools
      type: git
      name: ESODevTools
      ref: refs/heads/ado
name: $(BuildID)
trigger: none
pr:
  - master

variables:
  - group: TranslatorKey
  - name: AzureTranslatorKey
    value: $(ProvinatusTranslatorKey1)

jobs:
  - template: ./.ADO/pr.yml@ESODevTools
